#!/usr/bin/env bash

TEST_OUTPUT="tests/tmp"

clean() {
    # Clean up temporary files
    rm -rf "./tests/tmp"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}


function generate {
    copier copy -f --trust -r HEAD . "$TEST_OUTPUT" \
		-d testing=true \
		-d project_name="Testing" \
		-d project_description="Testing this great template" \
		-d author_fullname="John Doe" \
		-d author_username="joesgithub" \
		-d author_email="joe@example.com"
}


# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"